### ISSUE TITLE
Add open food facts products api repository

### ISSUE THREAD

**Issue by mrcsilverfox** [app-anvil/waste_not#2]
```
base_products_api_repository use an base_products_api_client_ to get the products from a barcode 
    - data:
        - data_source: 
        	- defines open_food_facts_api_client (concrete)
        - models: extends domain models
        - repository: extends domain repository and use data_source    
    - domain:
    	- base_products_api_client (abstract)
        - entities (concrete)
        - repositories (abstract)
```
